AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - _site/**/*
    - node_modules/**/*
    - vendor/**/*
    - blog.rb

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
