AllCops:
  TargetRubyVersion: 2.3.1
  Exclude:
    - _site/**/*
    - node_modules/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
