#bootstrap and build
before_script:
  - 'echo "branch: $TRAVIS_BRANCH" >> _config_test.yml'
  - 'sed -i "s/master/$TRAVIS_BRANCH/g" _config_test.yml'

script: "./script/cibuild"

language: ruby
rvm:
  - 2.1.4

sudo: false

env:
  global:
    NOKOGIRI_USE_SYSTEM_LIBRARIES=true
