permalink: /:categories/:year/:month/:day/:title.html

exclude: []
auto: true
server: true
server_port: 4000
pygments: true
markdown: rdiscount
title : fulcrum
tagline: mobile location leverage
url: http://colemanm.org
author :
  name : Coleman McCormick
  email : coleman@colemanm.org
  github : colemanm
  twitter : colemanm
  feedburner : http://colemanm.org/feed

production_url : colemanm.org

comments :
  provider : disqus
  disqus :
    short_name : jekyllbootstrap
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light
      
analytics :
  provider : google 
  google : 
      tracking_id : 'UA-15852145-5'