title: colemanm.org
name: colemanm.org
description: "Notes + Links from @colemanm"
author:
  name: Coleman McCormick
  email: coleman@colemanm.org
  uri: http://www.colemanm.org
permalink: /post/:title/
port: 4001
url: http://localhost:4001
relative_permalinks: false
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

collections:
  maps:
    output: true

feed:
  path: atom.xml

#files to exclude, array
exclude:
  - CONTRIBUTING.md
  - README.md
  - bundle
  - script
  - CNAME
  - Gemfile
  - Gemfile.lock
  - ".bundle"
  - vendor
