title: "colemanm.org"
name: "colemanm.org"
description: "Notes + Links from @colemanm"
author: Coleman McCormick
permalink: /post/:title/
port: 4001
url: http://www.colemanm.org
relative_permalinks: false
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

collections:
  maps:
    output: true

#files to exclude, array
exclude:
  - CONTRIBUTING.md
  - README.md
  - bundle
  - script
  - CNAME
  - Gemfile
  - Gemfile.lock
  - ".bundle"
  - vendor
