permalink: /post/:title/
port: 4001
url: http://www.colemanm.org
relative_permalinks: false
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

title: "colemanm.org"
description: "Notes + Links from @colemanm"
