url: "http://localhost:4001"

proofer:
  href_ignore:
    - !ruby/regexp '/https?:\/\/(www)?\.youtube\.com\/watch\?v=.*/i'
  :check_html: true
  :disable_external: true

github:
  repository_nwo: "colemanm/colemanm.github.com"
  owner_url: "https://github.com/colemanm"
