permalink: /post/:title/

exclude: []
port: 4001
pygments: true
markdown: kramdown
url: http://colemanm.org
author :
  name : Coleman McCormick
  email : coleman@colemanm.org
  github : colemanm
  twitter : colemanm