permalink: /post/:title/

exclude: []
auto: true
server: true
server_port: 4000
pygments: true
markdown: kramdown
url: http://colemanm.org
author :
  name : Coleman McCormick
  email : coleman@colemanm.org
  github : colemanm
  twitter : colemanm