backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow
media_folder: "images/post-images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "select"
        options:
          - { label: "Post", value: "post" }
          - { label: "Link", value: "link" }
        default: ["post"]
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Title", name: "title", widget: "string", default: "Title" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "img", widget: "image" }
      - { label: "Categories", name: "categories", widget: "hidden", default: "blog" }
      - label: "Tags"
        name: "tags"
        widget: "list"
      - { label: "Content", name: "body", widget: "markdown" }
      - label: "Links"
        name: "links"
        widget: "list"
        fields:
          - label: "Link"
            name: "url"
            widget: "string"
          - label: "Title"
            name: "title"
            widget: "string"